language = "rust"
tavily_api_key = "env:TAVILY_API_KEY"
tool_executor = "docker"

[commands]
test = "cargo test --no-fail-fast --color=never"
coverage = "cargo tarpaulin --skip-clean"

[github]
owner = "bosun-ai"
repository = "kwaak"
main_branch = "master"
token = "env:GITHUB_TOKEN"

[llm.indexing]
api_key = "env:KWAAK_OPENAI_API_KEY"
provider = "OpenAI"
prompt_model = "gpt-4o-mini"

[llm.query]
api_key = "env:KWAAK_OPENAI_API_KEY"
provider = "OpenAI"
prompt_model = "gpt-4o"

[llm.embedding]
api_key = "env:KWAAK_OPENAI_API_KEY"
provider = "OpenAI"
embedding_model = "text-embedding-3-large"

[docker]
dockerfile = "Dockerfile"
